### ISSUE TITLE
AWS configs in Rake `pull_asset`

### ISSUE THREAD

**Issue by Adeynack** [nerdgeschoss/shimmer#1]
https://github.com/nerdgeschoss/shimmer/blob/a5b75d6d307e8b04e97a4d056f32d40728480ed9/lib/shimmer/tasks/db.rake#L21-L26

On _Heroku_, those config are all prefixed with `S3_`. How can this _Rake_ task work?
Also, executing `heroku config --json` without the `-a APP_NAME` switch does not work.
Is this made to run only from another _Heroku_ app, or also locally?

**Comment by Adeynack** [comment]
Download worked, but then...

```
NameError: uninitialized constant ActiveStorage::VariantRecord
```

**Comment by Adeynack** [comment]
And `service_name` is no column in `ActiveStorage::Blob`.
Did those last 2 things appear in more recent versions of _Rails_?

**Comment by JensRavens** [comment]
- you need the newest version of activestorage for this to work (there's an upgrade guide in the guide of activstorage)
- we don't use S3 prefixes anymore as that was non-standard behaviour. The new env variables are named this way and match the documentation of the s3 gem
- the rake task assumes that you are connected to heroku via `heroku git:remote`. That way the task can be generic without any app specific settings.

**Comment by Adeynack** [comment]
So basically, I was trying that out on an outdates project?

**Comment by JensRavens** [comment]
now sure which project that was, but I'd say yes.
