### ISSUE TITLE
VideoCompressor

### ISSUE THREAD

**Issue by Adeynack** [nerdgeschoss/shimmer#28]
# AcceptanceCriteria

- [ ] class `VideoCompressor` is moved from _Anymator_ to _Shimmer_.
- [ ] PR is open in _Anymator_ to remove the code and use _Shimmer_ instead, waiting for this one to be merged.
- [ ] Usage is documented

**Comment by JensRavens** [comment]
I don't see this in shimmer. It's super project specific and I don't think we'll ever need this in another project.

**Comment by Adeynack** [comment]
I remember you @JensRavens saying it should be moved to shimmer when we reviewed that PR on _Anymator_ ;-) But I'll gladly drop it.

@jmarsh24: Please remove the `TODO: Move to Shimmer` comment in _Anymator_ at your earliest convenience.
