### ISSUE TITLE
Generic Stack Component

### ISSUE THREAD

**Issue by JensRavens** [nerdgeschoss/shimmer#44]
We reuse our `Stack` component across projects by now, but it would be great to have the same implementation (at least in new projects) everywhere.

**Acceptance Criteria**
- the breakpoints can be specified via css variables (`--size-breakpoint-tablet`, `--size-breakpoint-desktop`, `--size-breakpoint-widescreen`)
  - the default (therefore no breakpoint name for it) is _mobile_ (mobile first)
  - the breakpoints would be part of the project, not the component
- make sure all developers agree on the shaping document before implementation
- there's a css file in the npm module that can be manually required (e.g. by sprockets or vite-rails) that brings in the `stack` class
- there's a `Stack` react component that can be required (`import {Stack} from '@nerdgeschoss/shimmer/components/stack'`) which exposes all the settings as typed properties

**Comment by acidburnt** [comment]
After looking at the stack component in LAIC created by @leoggonzalez I think it makes sense to use it as a base here.


Supported sizes - [also based on LAIC](https://nerdgeschoss.slack.com/archives/C4VEDLJ1K/p1683537102022759)

```
--spacing-5xs: 2px;
--spacing-4xs: 4px;
--spacing-3xs: 8px;
--spacing-2xs: 12px;
--spacing-xs: 16px;
--spacing-sm: 20px;
--spacing-md: 22px;
--spacing-lg: 24px;
--spacing-xl: 32px;
--spacing-2xl: 40px;
--spacing-3xl: 48px;
--spacing-4xl: 56px;
--spacing-5xl: 64px;
```

As suggested by @JensRavens we could use different naming tho, so instead of `5xs`, `4xs` etc use numbers like `--spacing-1`, `--spacing-2`, `--spacing-3`


Props and helper types:
```ts
type Sizes = 'zero' | 'xxxs' | 'xxs' | 'xs' | 's' | 'm' | 'l' | 'xl' | 'xxl' | 'xxxl' | 'xxxxl' | 'mega';
// or as using numbers instead
type Sizes = '1' | '2' | '3' | '4' | '5' | '6' // etc.

// I updated left/right/top/bottom with start and end since we want to support revers and I think it general it makes more sense
type Justify = 'start' | 'center' | 'end' | 'space-between' | 'space-around';
type Align = 'start' | 'center' | 'end' | 'space-between';

interface Props {
// I think children should be one prop that is not optional
  children: React.ReactNode;
// default size should be 24px
  size?: Sizes;
  tabletSize?: Sizes;
  desktopSize?: Sizes;
  line?: boolean;
  tabletLine?: boolean;
  desktopLine?: boolean;
  align?: Align;
  justify?: Justify;
  tabletJustify?: Justify;
  desktopJustify?: Justify;
  reverse?: boolean;
  inline?: boolean;
}
```

Draft breakpoints - need confirmation for this one:

```
$breakpoint-phone: 375px; <- this one will be skipped since we do mobile first
$breakpoint-tablet: 640px;
$breakpoint-tablet-large: 740px;
$breakpoint-desktop: 890px;
$breakpoint-widescreen: 1280px;
```

**Comment by JensRavens** [comment]
- breakpoints should not be define outside of the component and just used by the component, therefore the actual values don't matter
- if we have a `desktopJustify`, where's the `widescreenJustify`?
- we should probably go through a few use cases and what the props would be then (it feels currently like you need a lot of modifiers in line-mode)
- maybe let's switch `tabletLine` to `lineTablet`, then all of the different line breakpoints would appear next to each other in autocomplete
- the sizes should represent actual pixel values. I don't want to keep a conversion table in my head where I constantly have to figure out if xs is 4 or 8 pixels. just renaming it doesn't solve that. it should be `stack--4` for a 4px gap, no variables required.
- do we really need inline and reverse? If yes, then probably they should have corresponding breakpoint versions

**Comment by acidburnt** [comment]
I updated my initial comment, removed reverse and inline - after thinking about it I don't think it will bring much value.


some examples
```tsx
<Stack size="16"  justify="start" lineWidescreen justifyWideScreen="center">
  <div>one</div>
  <div>two</div>
  <div>three</div>
</Stack>
```

```slim
.stack.stack--16.stack--justify-start.stack--line-widescreen.stack--justify-widescreen-center
  div one
  div two
  div three
```

yeah, there will be a lot of modifiers but if we want to keep the comp generic I don't see how to avoid it

also, @JensRavens  what are your thoughts on Tailwind? 😄

**Comment by JensRavens** [comment]
I tried to make a bit more sense out of it by trying it visually [in figma](https://www.figma.com/file/UjmjKeJVeyIkxmkTtKlPHk/Stack-Component?type=design&node-id=0%3A1&t=NbVCqGMjyPLDc3P0-1), that's also where I found a few missing bits.

- your current types mix align and justify in the types
- the stretch use-case is very common but is missing here
- if we put the modified (desktop, widescreen, etc) at the end, the same should be true for `size`
- let's rename `size` to `gap`, that's a lot more precise on what it's doing. the default should be 8 as this is the most common gap used in designs. don't forget a gap of 0 and let's make that a number instead of an enum (at least for react, for the css version of course we need a fixed list) so we don't have to constantly extend it whenever designers come up with a new spacing
- we don't need a `tablet-large` breakpoint, also you can remove the css variable names for spacing sizes and just replace them with a list of supported gaps

**Comment by acidburnt** [comment]
Added next set of improvements to the original comment.
However, I now realized we cannot use CSS variables for media queries like:

```css
@media screen and (min-width: var(--mobile)) {
  
}
```

is the implementation gonna be in SCSS then?

**Comment by JensRavens** [comment]
I asked a question about [hardcoding it on slack](https://nerdgeschoss.slack.com/archives/C02TSHV4FHN/p1685543022876739).  Otherwise, it would be hardcoded with scss variables (but that would require scss on usage site).

**Comment by JensRavens** [comment]
Got some feedback on it - let's go for the scss solution then so we can keep variable breakpoints.

**Comment by leoggonzalez** [comment]
Check rollup config of the use form library to figure out how to serve react components:

https://github.com/nerdgeschoss/react-use-form-library/blob/master/rollup.config.js
